Repository Jayllyz/escape-react, pull requests merged in 2024-07, with the labels that each got.

#16 feat: add Login page
  api/db.json
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Header.tsx
  src/lib/validators.ts
  src/main.tsx
  src/pages/EmployeeDashboard.tsx
  src/pages/Login.tsx
Labels: enhancement

#17 chore: setup unit tests
  .github/workflows/ci.yml
  farm.config.ts
  package.json
  pnpm-lock.yaml
  tests/unit.test.ts
  tsconfig.json
  tsconfig.node.json
  vitest.config.ts
Labels: maintenance

#19 feat: session table
  src/components/ui/SessionsRow.tsx
  src/components/ui/SessionsTable.tsx
  src/lib/api.ts
  src/pages/EmployeeDashboard.tsx
Labels: enhancement

#20 feat: cancel/restore sessions
  api/db.json
  src/components/ui/CancelSlot.tsx
  src/components/ui/RestoreSlot.tsx
  src/components/ui/SessionsTable.tsx
  src/lib/api.ts
  src/lib/types.ts
  src/main.tsx
  src/pages/EmployeeSession.tsx
Labels: enhancement

#21 fix: working fetches
  api/db.json
  src/components/ui/CancelSlot.tsx
  src/components/ui/RestoreSlot.tsx
  src/components/ui/SessionsTable.tsx
  src/lib/api.ts
  src/lib/types.ts
  src/pages/EmployeeSession.tsx
Labels: fix

#22 feat: finished sessions feature
  api/db.json
  src/components/ui/BookingForm.tsx
  src/components/ui/ContactForm.tsx
  src/components/ui/EmployeeSession/CancelSlot.tsx
  src/components/ui/EmployeeSession/CreateSlot.tsx
  src/components/ui/EmployeeSession/DeleteSlot.tsx
  src/components/ui/EmployeeSession/EditSession.tsx
  src/components/ui/EmployeeSession/RestoreSlot.tsx
  src/lib/api.ts
  src/pages/EmployeeSession.tsx
Labels: enhancement

#23 feat: admin for employees and sessions
  api/db.json
  src/components/ui/AdminEmployee/Activate.tsx
  src/components/ui/AdminEmployee/Deactivate.tsx
  src/components/ui/AdminSession/CreateSession.tsx
  src/components/ui/SessionsTable.tsx
  src/lib/api.ts
  src/lib/types.ts
  src/main.tsx
  src/pages/AdminEmployee.tsx
  src/pages/AdminSession.tsx
  src/pages/EmployeeDashboard.tsx
  src/pages/Login.tsx
Labels: enhancement

#25 feat: dark mode
  src/App.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/ui/BookingForm.tsx
  src/components/ui/ContactForm.tsx
  src/pages/AdminEmployee.tsx
  src/pages/AdminSession.tsx
  src/pages/EmployeeDashboard.tsx
  src/pages/EmployeeSession.tsx
  src/pages/Login.tsx
  src/pages/Session.tsx
Labels: enhancement

#26 feat: admin bookings
  api/db.json
  src/components/ui/AdminBooking/ConfirmBooking.tsx
  src/components/ui/AdminBooking/DenyBooking.tsx
  src/components/ui/AdminSession/CreateSession.tsx
  src/components/ui/Session/BookSlot.tsx
  src/lib/api.ts
  src/lib/types.ts
  src/main.tsx
  src/pages/AdminBooking.tsx
  src/pages/EmployeeDashboard.tsx
  src/pages/EmployeeSession.tsx
  src/pages/Login.tsx
  src/pages/Session.tsx
Labels: enhancement
